### ISSUE TITLE
Instructions for installation

### ISSUE THREAD

**Issue by bobbych** [lensacom/sparkit-learn#10]
Are there any instructions to use it on spark cluster? looks like its not integrated with spark packages. Any help is appreciated

**Comment by kszucs** [comment]
You could either zip the module on driver driver side and use sc.addPyFiles, or install with pip on each node. We are planning to distribute on PyPI right after the first release.

**Comment by cubreto** [comment]
Ok thanks. I figured a way to do it by reading the Travis.yml hidden file. In any case, if you want me to contribute assign me some Jira tickets. 

Thanks 
Guillermo.

**Comment by cubreto** [comment]
This functionality is great (addpyfiles). However doesn't  splearn depend on scikit learn? Does that mean I also have to zip scikit learn and add it? And for that matter doesn't scikit learn use numpy and do I need to also zip numpy an so forth? And finally, if the Python module needs C for their cythonic computations are the executors able to run the the C code? I imagine it will happen as if by magic as long as the driver has all the packages available spark should be able to serialize the code and run it on the executors. 

I noticed you are putting some tasks. I'll start working on some of those. 

Best, Guillermo

**Comment by kszucs** [comment]
I suggest You to have the scipy stack installed on the executor (worker) nodes too. Since yesterday sparkit is on PyPI.
