### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by mrshanth** [lensacom/sparkit-learn#32]
I am getting syntax errors in
 * splearn/base.py :
   -  for name in self.__transient__}, line 12
 * splearn/feature_extraction/text.py :
   -  vocabulary = {t: i for i, t in enumerate(accum.value)}, line 154

**Comment by nralat** [comment]
Which python version do you use? Dictionary comprehension come with Python 2.7
https://www.python.org/dev/peps/pep-0274/

**Comment by mrshanth** [comment]
We are using Python 2.6.6 in Centos 6.5. 
I will update and check. Thanks.
