### ISSUE TITLE
TypeError: 'Broadcast' object is unsubscriptable

### ISSUE THREAD

**Issue by mrshanth** [lensacom/sparkit-learn#34]
We are trying to create a Count Vector using SparkCountVectorizer. We are using Python 2.6.6, hence
replaced all the dict_comprehensions in the code. We ran into this following error:
```
  File "base.py", line 19, in func_wrapper
    return func(*args, **kwargs)
  File "splearn_custom.py", line 176, in _count_vocab
    j_indices.append(vocabulary[feature])
TypeError: 'Broadcast' object is unsubscriptable
```
Here, splearn_custom.py refers to feature_extraction/text.py

Thanks in advance

**Comment by kszucs** [comment]
Could You paste the whole stack trace?

**Comment by kszucs** [comment]
Closed due to inactivity.
