### ISSUE TITLE
Spark version 1.2.1, error AttributeError: <class 'rdd.BlockRDD'> object has no attribute treeReduce

### ISSUE THREAD

**Issue by vishalrajpal25** [lensacom/sparkit-learn#37]
>>> countvectorizer = SparkCountVectorizer(tokenizer=tokenize_pre_process)
>>> count_vector
<class 'rdd.ArrayRDD'> from PythonRDD[22] at collect at rdd.py:168
>>> sel_vt = SparkVarianceThreshold()
>>> red_vt_vector = sel_vt.fit_transform(count_vector)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "base.py", line 63, in fit_transform
    return self.fit(Z, **fit_params).transform(Z)
  File "feature_selection.py", line 72, in fit
    _, _, self.variances_ = X.map(mapper).treeReduce(reducer)
  File "rdd.py", line 179, in __getattr__
    self.__class__, attr))
AttributeError: <class 'rdd.BlockRDD'> object has no attribute treeReduce

I am using spark 1.2.1, and I think rdd has the method treeReduce. 
Would you have any idea why this error could be popping out of the ArrayRDD extendig BlockRDD

**Comment by kszucs** [comment]
I've successfully reproduced the issue and pyspark.RDD doesn't have the method treeReduce, see https://github.com/apache/spark/blob/branch-1.2/python/pyspark/rdd.py

If You can't update spark, I suggest to change `treeReduce` to `reduce`.

Right now, the spark version support is an ongoing discussion. We'll update the reqiurements in the README.

**Comment by vishalrajpal25** [comment]
Thanks for the solution. We can't update spark yet so will change the method to reduce on rdd
