### ISSUE TITLE
Invalid syntax issue

### ISSUE THREAD

**Issue by raghunittala** [lensacom/sparkit-learn#5]
When running splearn/feature_extraction/text.py using pyspark shell, I am getting invalid syntax at :
vocabulary = {t: i for i, t in enumerate(accum.value)}

python 2.6.6
spark 1.2.0
numpy 1.9.0
scikit 1.5.2

If anappropriate to put the issue details here, please redirect the same. Thanks in advance

**Comment by fulibacsi** [comment]
Thank you for looking into our library and reporting! The purpose of the syntax error is that dict comprehension was introduced in Python 2.7. We will specify that in the requirements. Unrelated, but scikit-learn 0.16 is also required.
