### ISSUE TITLE
DBSCAN Import Error

### ISSUE THREAD

**Issue by Elbehery** [lensacom/sparkit-learn#55]
I have been trying to run DBSCAN, using Python from command line .. I got this error 

**ImportError: cannot import name _get_unmangled_double_vector_rdd** 

 Any one can help me regarding this ?

**Comment by Elbehery** [comment]
I think I got the issue, the according to this https://fossies.org/diffs/spark/1.1.1_vs_1.2.0/python/pyspark/mllib/stat.py-diff.html, PySpark has changed the MLib implementation, so the _get_unmangled_double_vector_rdd does not exist any more .. Anyone can fix this ??

**Comment by Elbehery** [comment]
@kszucs can you help me with this ?

**Comment by kszucs** [comment]
The DBSCAN python API is outdated and will be removed in the upcoming branch. Have You tried using https://github.com/alitouka/spark_dbscan from scala?

**Comment by Elbehery** [comment]
Indeed .. Although this implementation works perfectly for the provided sample data, its not working at all for any other data. I have spent around 10 days trying to make it work, I have used portion of my data, with is typically the number of records, and dimensions as the sample data, but it did not work. Although I have tried all the tuning parameters of SparkConf, did not work as well. 

This implementation has a bottleneck of aggregation step, in which the partitions are merged, according to the provided wiki https://github.com/alitouka/spark_dbscan/wiki/Density-based-partitioning. I have used monitoring tools to watch what exactly happens, and the algorithm at this certain step is turned into **sequential** and the computation kept running and never ends.

I have tried to communicate with the author over git and mail and there were no response at all. 

Please let me know if you have any suggestion since I need to use DBSCAN to cluster around 1.5G of data. 

Thanks in advance

**Comment by kszucs** [comment]
There is another one: https://github.com/irvingc/dbscan-on-spark 
Based on the visualization it could be easily inplemented with `sparkit-learn` via applying scikit's DBSCAN on the blocks.

**Comment by Elbehery** [comment]
@kszucs  Thanks a lot .. Can u give me more hints about how to apply it, or similar example if possible ?
